[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_badge.csv
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DARDUINO_LOOP_STACK_SIZE=16384

lib_deps =
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit SSD1306@^2.5.15
    adafruit/Adafruit NeoPixel@^1.12.0

